# Generated by Django 5.1.6 on 2025-03-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
