# Generated by Django 5.1.6 on 2025-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='series',
            field=models.IntegerField(),
        ),
    ]
