# Generated by Django 5.1.2 on 2025-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_1',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_2',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_3',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_4',
            field=models.ImageField(default=1, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
