# Generated by Django 5.1.2 on 2025-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_banner_image_1_banner_image_2_banner_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='enable_floating',
            field=models.BooleanField(default=False),
        ),
    ]
