# Generated by Django 5.1.6 on 2025-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
