# Generated by Django 5.1.6 on 2025-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_supplier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
