# Generated by Django 5.1.6 on 2025-04-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_supplier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_location',
            field=models.TextField(blank=True, help_text="Comma-separated iframe codes for multiple locations. Example: '<iframe...>,<iframe...>'", null=True),
        ),
    ]
