# Generated by Django 5.1.6 on 2025-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_supplier_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shortcut_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_shortcut_images/'),
        ),
    ]
