# Generated by Django 5.1.6 on 2025-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_shortcut_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
