# Generated by Django 5.1.2 on 2025-04-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ytlink_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
