# Generated by Django 5.1.2 on 2025-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_youtube_url_product_ytlink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_url',
            field=models.CharField(max_length=5000),
        ),
    ]
