# Generated by Django 5.1.6 on 2025-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogues',
            field=models.FileField(blank=True, null=True, upload_to='catalogues/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
